; platformio.ini
[platformio]
extra_configs = config.ini
[base]
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/KingsBeCattz/MotorDriveUnit.git#main
; ─── ESP32 bases ───────────────────────────────────────────────
[esp32-base]
extends = base
platform = espressif32
board = esp32doit-devkit-v1
platform_packages =
  framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
[esp32-toolchain]
platform_packages =
  espressif/toolchain-xtensa-esp32@12.2.0+20230208
  ${esp32-base.platform_packages}
; ─── Arduino bases ─────────────────────────────────────────────
[arduino-base]
extends = base
platform = atmelavr
board = uno
lib_deps =
  ${base.lib_deps}
  https://github.com/madsci1016/Arduino-PS2X.git
; ─── ESP32 Envs ────────────────────────────────────────────
[env:esp32-l298n]
extends = esp32-base
platform_packages = ${esp32-toolchain.platform_packages}
build_flags =
  ${config_l298n.build_flags}
[env:esp32-tb6612fng]
extends = esp32-base
platform_packages = ${esp32-toolchain.platform_packages}
build_flags =
  ${config_tb6612fng.build_flags}
[env:esp32-bts7960]
extends = esp32-base
platform_packages = ${esp32-toolchain.platform_packages}
build_flags =
  ${config_bts7960.build_flags}
[env:esp32-bts7960-dual]
extends = esp32-base
platform_packages = ${esp32-toolchain.platform_packages}
build_flags =
  ${config_bts7960_dual.build_flags}
; ─── Arduino Envs ──────────────────────────────────────────
[env:arduino-l298n]
extends = arduino-base
build_flags =
  ${config_l298n.build_flags}
[env:arduino-tb6612fng]
extends = arduino-base
build_flags =
  ${config_tb6612fng.build_flags}
[env:arduino-bts7960]
extends = arduino-base
build_flags =
  ${config_bts7960.build_flags}